version: "2"
services:
  driver-service:
    image: driver-service
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always